package net.amentum.niomedic.expediente.converter.historia_clinica_general.interrogatorio_aparatos;

import net.amentum.niomedic.expediente.model.historia_clinica.interrogatorio_aparatos.InterrogatorioSistemaNervioso;
import net.amentum.niomedic.expediente.views.historia_clinica_general.interrogatorio_aparatos.InterrogatorioSistemaNerviosoView;
import org.springframework.stereotype.Component;

@Component
public class InterrogatorioSistemaNerviosoConverter {

    public InterrogatorioSistemaNervioso toEntity(InterrogatorioSistemaNerviosoView view) {
        InterrogatorioSistemaNervioso entity = new InterrogatorioSistemaNervioso();
        entity.setIdInterrogatorio(view.getIdInterrogatorio());
        entity.setIdHistoriaClinica(view.getIdHistoriaClinica());
        entity.setNervioAsintomatico(view.getNervioAsintomatico());
        entity.setSuenioCantidad(view.getSuenioCantidad());
        entity.setSuenioReparador(view.getSuenioReparador());
        entity.setSomnolencia(view.getSomnolencia());
        entity.setEpilepsia(view.getEpilepsia());
        entity.setInsomnioTiempoEvol(view.getInsomnioTiempoEvol());
        entity.setInsomnioCaracteristicas(view.getInsomnioCaracteristicas());
        entity.setInsomnioTratamiento(view.getInsomnioTratamiento());
        entity.setDolorTipoSelect(view.getDolorTipoSelect());
        entity.setConvulsionesFrecuencia(view.getConvulsionesFrecuencia());
        entity.setConvulsionesNumero(view.getConvulsionesNumero());
        entity.setConvulsionesOtro(view.getConvulsionesOtro());
        entity.setMigraniaLocalizacion(view.getMigraniaLocalizacion());
        entity.setMigraniaCaracteristicas(view.getMigraniaCaracteristicas());
        entity.setMigraniaTiempoEvol(view.getMigraniaTiempoEvol());
        entity.setMigraniaTratamiento(view.getMigraniaTratamiento());
        entity.setPerdidaEquilibrioCaracteristicas(view.getPerdidaEquilibrioCaracteristicas());
        entity.setPerdidaEquilibrioTiempoEvol(view.getPerdidaEquilibrioTiempoEvol());
        entity.setPerdidaEquilibrioTratamiento(view.getPerdidaEquilibrioTratamiento());
        entity.setHiposensibilidadLocalizacion(view.getHiposensibilidadLocalizacion());
        entity.setHiposensibilidadTiempoEvol(view.getHiposensibilidadTiempoEvol());
        entity.setAlodiniaLocalizacion(view.getAlodiniaLocalizacion());
        entity.setAlodiniaTiempoEvol(view.getAlodiniaTiempoEvol());
        entity.setParestesiasLocalizacion(view.getParestesiasLocalizacion());
        entity.setParestesiasTiempoEvol(view.getParestesiasTiempoEvol());
        entity.setParkinson(view.getParkinson());
        entity.setParkinsonCaracteristicas(view.getParkinsonCaracteristicas());
        entity.setParkinsonTiempoEvol(view.getParkinsonTiempoEvol());
        entity.setParkinsonTratamiento(view.getParkinsonTratamiento());
        entity.setPerdidaConcienciaCaracteristicas(view.getPerdidaConcienciaCaracteristicas());
        entity.setPerdidaConcienciaTiempoEvol(view.getPerdidaConcienciaTiempoEvol());
        entity.setPerdidaConcienciaCausa(view.getPerdidaConcienciaCausa());
        entity.setPerdidaConcienciaTratamiento(view.getPerdidaConcienciaTratamiento());
        entity.setHipersensibilidad(view.getHipersensibilidad());
        entity.setHipersensibilidadLocalizacion(view.getHipersensibilidadLocalizacion());
        entity.setHipersensibilidadTiempoEvol(view.getHipersensibilidadTiempoEvol());
        entity.setHiperalgesiaLocalizacion(view.getHiperalgesiaLocalizacion());
        entity.setHiperalgesiaTiempoEvol(view.getHiperalgesiaTiempoEvol());
        entity.setPerdidaMemoriaCaracteristicas(view.getPerdidaMemoriaCaracteristicas());
        entity.setPerdidaMemoriaTiempoEvol(view.getPerdidaMemoriaTiempoEvol());
        entity.setPerdidaMemoriaCausa(view.getPerdidaMemoriaCausa());
        entity.setPerdidaMemoriaTratamiento(view.getPerdidaMemoriaTratamiento());
        entity.setComentarios(view.getComentarios());
        entity.setEstuporoso(view.getEstuporoso());
        entity.setMareos(view.getMareos());
        entity.setVertigo(view.getVertigo());
        entity.setHipersomnia(view.getHipersomnia());
        entity.setHiposomnia(view.getHiposomnia());
        entity.setCefalea(view.getCefalea());
        entity.setMovimientosInvoluntarios(view.getMovimientosInvoluntarios());
        entity.setTics(view.getTics());
        entity.setNistagmo(view.getNistagmo());
        entity.setMarchaInestable(view.getMarchaInestable());
        entity.setTemblor(view.getTemblor());
        entity.setCalambresMusculares(view.getCalambresMusculares());
        entity.setDebilidadMuscular(view.getDebilidadMuscular());
        entity.setHiperestesia(view.getHiperestesia());
        entity.setHipoestesia(view.getHipoestesia());
        entity.setDisestesia(view.getDisestesia());
        entity.setHiperpatia(view.getHiperpatia());
        return entity;
    }

    public InterrogatorioSistemaNerviosoView toView(InterrogatorioSistemaNervioso entity) {
        InterrogatorioSistemaNerviosoView view = new InterrogatorioSistemaNerviosoView();
        view.setIdInterrogatorio(entity.getIdInterrogatorio());
        view.setIdHistoriaClinica(entity.getIdHistoriaClinica());
        view.setNervioAsintomatico(entity.getNervioAsintomatico());
        view.setSuenioCantidad(entity.getSuenioCantidad());
        view.setSuenioReparador(entity.getSuenioReparador());
        view.setSomnolencia(entity.getSomnolencia());
        view.setEpilepsia(entity.getEpilepsia());
        view.setInsomnioTiempoEvol(entity.getInsomnioTiempoEvol());
        view.setInsomnioCaracteristicas(entity.getInsomnioCaracteristicas());
        view.setInsomnioTratamiento(entity.getInsomnioTratamiento());
        view.setDolorTipoSelect(entity.getDolorTipoSelect());
        view.setConvulsionesFrecuencia(entity.getConvulsionesFrecuencia());
        view.setConvulsionesNumero(entity.getConvulsionesNumero());
        view.setConvulsionesOtro(entity.getConvulsionesOtro());
        view.setMigraniaLocalizacion(entity.getMigraniaLocalizacion());
        view.setMigraniaCaracteristicas(entity.getMigraniaCaracteristicas());
        view.setMigraniaTiempoEvol(entity.getMigraniaTiempoEvol());
        view.setMigraniaTratamiento(entity.getMigraniaTratamiento());
        view.setPerdidaEquilibrioCaracteristicas(entity.getPerdidaEquilibrioCaracteristicas());
        view.setPerdidaEquilibrioTiempoEvol(entity.getPerdidaEquilibrioTiempoEvol());
        view.setPerdidaEquilibrioTratamiento(entity.getPerdidaEquilibrioTratamiento());
        view.setHiposensibilidadLocalizacion(entity.getHiposensibilidadLocalizacion());
        view.setHiposensibilidadTiempoEvol(entity.getHiposensibilidadTiempoEvol());
        view.setAlodiniaLocalizacion(entity.getAlodiniaLocalizacion());
        view.setAlodiniaTiempoEvol(entity.getAlodiniaTiempoEvol());
        view.setParestesiasLocalizacion(entity.getParestesiasLocalizacion());
        view.setParestesiasTiempoEvol(entity.getParestesiasTiempoEvol());
        view.setParkinson(entity.getParkinson());
        view.setParkinsonCaracteristicas(entity.getParkinsonCaracteristicas());
        view.setParkinsonTiempoEvol(entity.getParkinsonTiempoEvol());
        view.setParkinsonTratamiento(entity.getParkinsonTratamiento());
        view.setPerdidaConcienciaCaracteristicas(entity.getPerdidaConcienciaCaracteristicas());
        view.setPerdidaConcienciaTiempoEvol(entity.getPerdidaConcienciaTiempoEvol());
        view.setPerdidaConcienciaCausa(entity.getPerdidaConcienciaCausa());
        view.setPerdidaConcienciaTratamiento(entity.getPerdidaConcienciaTratamiento());
        view.setHipersensibilidad(entity.getHipersensibilidad());
        view.setHipersensibilidadLocalizacion(entity.getHipersensibilidadLocalizacion());
        view.setHipersensibilidadTiempoEvol(entity.getHipersensibilidadTiempoEvol());
        view.setHiperalgesiaLocalizacion(entity.getHiperalgesiaLocalizacion());
        view.setHiperalgesiaTiempoEvol(entity.getHiperalgesiaTiempoEvol());
        view.setPerdidaMemoriaCaracteristicas(entity.getPerdidaMemoriaCaracteristicas());
        view.setPerdidaMemoriaTiempoEvol(entity.getPerdidaMemoriaTiempoEvol());
        view.setPerdidaMemoriaCausa(entity.getPerdidaMemoriaCausa());
        view.setPerdidaMemoriaTratamiento(entity.getPerdidaMemoriaTratamiento());
        view.setComentarios(entity.getComentarios());
        view.setEstuporoso(entity.getEstuporoso());
        view.setMareos(entity.getMareos());
        view.setVertigo(entity.getVertigo());
        view.setHipersomnia(entity.getHipersomnia());
        view.setHiposomnia(entity.getHiposomnia());
        view.setCefalea(entity.getCefalea());
        view.setMovimientosInvoluntarios(entity.getMovimientosInvoluntarios());
        view.setTics(entity.getTics());
        view.setNistagmo(entity.getNistagmo());
        view.setMarchaInestable(entity.getMarchaInestable());
        view.setTemblor(entity.getTemblor());
        view.setCalambresMusculares(entity.getCalambresMusculares());
        view.setDebilidadMuscular(entity.getDebilidadMuscular());
        view.setHiperestesia(entity.getHiperestesia());
        view.setHipoestesia(entity.getHipoestesia());
        view.setDisestesia(entity.getDisestesia());
        view.setHiperpatia(entity.getHiperpatia());
        return view;
    }
}
