package net.amentum.niomedic.expediente.converter.historia_clinica_general.interrogatorio_aparatos;

import net.amentum.niomedic.expediente.model.historia_clinica.interrogatorio_aparatos.InterrogatorioRespiratorio;
import net.amentum.niomedic.expediente.views.historia_clinica_general.interrogatorio_aparatos.InterrogatorioRespiratorioView;
import org.springframework.stereotype.Component;

@Component
public class InterrogatorioRespiratorioConverter {

    public InterrogatorioRespiratorio toEntity(InterrogatorioRespiratorioView view) {
        InterrogatorioRespiratorio entity = new InterrogatorioRespiratorio();
        entity.setIdInterrogatorio(view.getIdInterrogatorio());
        entity.setIdHistoriaClinica(view.getIdHistoriaClinica());
        entity.setResAsintomatico(view.getResAsintomatico());
        entity.setDolorToracico(view.getDolorToracico());
        entity.setDolorToracicoEvolucion(view.getDolorToracicoEvolucion());
        entity.setDolorToracicoTratamiento(view.getDolorToracicoTrata());
        entity.setHemoptisis(view.getHemoptisis());
        entity.setHemoptisisEvolucion(view.getHemoptisisEvolucion());
        entity.setHemoptisisTratamiento(view.getHemoptisisTrata());
        entity.setCianosis(view.getCianosis());
        entity.setCianosisEvolucion(view.getCianosisEvolucion());
        entity.setCianosisTratamiento(view.getCianosisTrata());
        entity.setOrtopnea(view.getOrtopnea());
        entity.setHumpro(view.getHumpro());
        entity.setHumnopro(view.getHumnopro());
        entity.setTosSeca(view.getToseca());
        entity.setHipo(view.getHipo());
        entity.setSilvidores(view.getSilvidores());
        entity.setAlmohadasDuerme(view.getAlmohadasDuerme());
        entity.setEstornudos(view.getEstornudos());
        entity.setEstornudosSalva(view.getEstornudosSalva());
        entity.setRinitis(view.getRinitis());
        entity.setRinititsEvolucion(view.getRinititsEvolucion());
        entity.setRinitisTratamiento(view.getRinitisTrata());
        entity.setDolorMandibular(view.getDolorMandibular());
        entity.setMandibularDerecha(view.getMandibularDerecha());
        entity.setMandibularIzquierda(view.getMandibularIzquierda());
        entity.setDiaforesis(view.getDiaforesis());
        entity.setDiaforesisInput(view.getDiaforesisInput());
        entity.setDisnea(view.getDisnea());
        entity.setDisneaMotivo(view.getDisneaMotivo());
        entity.setDisneaGesfuerzos(view.getDisneaGesfuerzos());
        entity.setDisneaMesfuerzos(view.getDisneaMesfuerzos());
        entity.setDisneaPesfuerzos(view.getDisneaPesfuerzos());
        entity.setDisneaEvolucion(view.getDisneaEvolucion());
        entity.setUsoOxigeno(view.getUsoOxigeno());
        entity.setOxigenoEvolucion(view.getOxigenoEvolucion());
        entity.setRinorreaSi(view.getRinorreaSi());
        entity.setRinorrea(view.getRinorrea());
        entity.setRinolaliaSi(view.getRinolaliaSi());
        entity.setRinolalia(view.getRinolalia());
        entity.setDisfonia(view.getDisfonia());
        entity.setDisfoniaEvolucion(view.getDisfoniaEvolucion());
        entity.setDisfoniaTratamiento(view.getDisfoniaTratamiento());
        entity.setAmigdalitis(view.getAmigdalitis());
        entity.setAmigdalitisFrecuencia(view.getAmigdalitisFrecuencia());
        entity.setAmigdalitisEvolucion(view.getAmigdalitisEvolucion());
        entity.setAmigdalitisTratamiento(view.getAmigdalitisTratamiento());
        entity.setExpectoracion(view.getExpectoracion());
        entity.setExpecTipo(view.getExpecTipo());
        entity.setExpecVerde(view.getExpecVerde());
        entity.setExpecAmarilla(view.getExpecAmarilla());
        entity.setExpecTransparente(view.getExpecTransparente());
        entity.setExpecBlanquecina(view.getExpecBlanquecina());
        entity.setExpecEvolucion(view.getExpecEvolucion());
        entity.setExpecTratamiento(view.getExpecTratamiento());
        entity.setFaringitis(view.getFaringitis());
        entity.setFaringitisEvolucion(view.getFaringitisEvolucion());
        entity.setFaringitisTratamiento(view.getFaringitisTratamiento());
        entity.setDolorTorax(view.getDolorTorax());
        entity.setDolorToraxEvolucion(view.getDolorToraxEvolucion());
        entity.setDolorToraxTratamiento(view.getDolorToraxTratamiento());
        entity.setRuidos(view.getRuidos());
        entity.setRuidosFrecuencia(view.getRuidosFrecuencia());
        entity.setRuidosEvolucion(view.getRuidosEvolucion());
        entity.setComentarios(view.getComentarios());
        return entity;
    }

    public InterrogatorioRespiratorioView toView(InterrogatorioRespiratorio entity) {
        InterrogatorioRespiratorioView view = new InterrogatorioRespiratorioView();
        view.setIdInterrogatorio(entity.getIdInterrogatorio());
        view.setIdHistoriaClinica(entity.getIdHistoriaClinica());
        view.setResAsintomatico(entity.getResAsintomatico());
        view.setDolorToracico(entity.getDolorToracico());
        view.setDolorToracicoEvolucion(entity.getDolorToracicoEvolucion());
        view.setDolorToracicoTrata(entity.getDolorToracicoTratamiento());
        view.setHemoptisis(entity.getHemoptisis());
        view.setHemoptisisEvolucion(entity.getHemoptisisEvolucion());
        view.setHemoptisisTrata(entity.getHemoptisisTratamiento());
        view.setCianosis(entity.getCianosis());
        view.setCianosisEvolucion(entity.getCianosisEvolucion());
        view.setCianosisTrata(entity.getCianosisTratamiento());
        view.setOrtopnea(entity.getOrtopnea());
        view.setHumpro(entity.getHumpro());
        view.setHumnopro(entity.getHumnopro());
        view.setToseca(entity.getTosSeca());
        view.setHipo(entity.getHipo());
        view.setSilvidores(entity.getSilvidores());
        view.setAlmohadasDuerme(entity.getAlmohadasDuerme());
        view.setEstornudos(entity.getEstornudos());
        view.setEstornudosSalva(entity.getEstornudosSalva());
        view.setRinitis(entity.getRinitis());
        view.setRinititsEvolucion(entity.getRinititsEvolucion());
        view.setRinitisTrata(entity.getRinitisTratamiento());
        view.setDolorMandibular(entity.getDolorMandibular());
        view.setMandibularDerecha(entity.getMandibularDerecha());
        view.setMandibularIzquierda(entity.getMandibularIzquierda());
        view.setDiaforesis(entity.getDiaforesis());
        view.setDiaforesisInput(entity.getDiaforesisInput());
        view.setDisnea(entity.getDisnea());
        view.setDisneaMotivo(entity.getDisneaMotivo());
        view.setDisneaGesfuerzos(entity.getDisneaGesfuerzos());
        view.setDisneaMesfuerzos(entity.getDisneaMesfuerzos());
        view.setDisneaPesfuerzos(entity.getDisneaPesfuerzos());
        view.setDisneaEvolucion(entity.getDisneaEvolucion());
        view.setUsoOxigeno(entity.getUsoOxigeno());
        view.setOxigenoEvolucion(entity.getOxigenoEvolucion());
        view.setRinorreaSi(entity.getRinorreaSi());
        view.setRinorrea(entity.getRinorrea());
        view.setRinolaliaSi(entity.getRinolaliaSi());
        view.setRinolalia(entity.getRinolalia());
        view.setDisfonia(entity.getDisfonia());
        view.setDisfoniaEvolucion(entity.getDisfoniaEvolucion());
        view.setDisfoniaTratamiento(entity.getDisfoniaTratamiento());
        view.setAmigdalitis(entity.getAmigdalitis());
        view.setAmigdalitisFrecuencia(entity.getAmigdalitisFrecuencia());
        view.setAmigdalitisEvolucion(entity.getAmigdalitisEvolucion());
        view.setAmigdalitisTratamiento(entity.getAmigdalitisTratamiento());
        view.setExpectoracion(entity.getExpectoracion());
        view.setExpecTipo(entity.getExpecTipo());
        view.setExpecVerde(entity.getExpecVerde());
        view.setExpecAmarilla(entity.getExpecAmarilla());
        view.setExpecTransparente(entity.getExpecTransparente());
        view.setExpecBlanquecina(entity.getExpecBlanquecina());
        view.setExpecEvolucion(entity.getExpecEvolucion());
        view.setExpecTratamiento(entity.getExpecTratamiento());
        view.setFaringitis(entity.getFaringitis());
        view.setFaringitisEvolucion(entity.getFaringitisEvolucion());
        view.setFaringitisTratamiento(entity.getFaringitisTratamiento());
        view.setDolorTorax(entity.getDolorTorax());
        view.setDolorToraxEvolucion(entity.getDolorToraxEvolucion());
        view.setDolorToraxTratamiento(entity.getDolorToraxTratamiento());
        view.setRuidos(entity.getRuidos());
        view.setRuidosFrecuencia(entity.getRuidosFrecuencia());
        view.setRuidosEvolucion(entity.getRuidosEvolucion());
        view.setComentarios(entity.getComentarios());
        return view;
    }

}
